# Generated by Django 4.2.2 on 2023-06-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('max_seats', models.PositiveIntegerField()),
                ('booking_open_window_start', models.DateTimeField()),
                ('booking_open_window_end', models.DateTimeField()),
            ],
        ),
    ]
