# Generated by Django 4.2.2 on 2023-06-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_created_at_event_created_by_event_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
